### PR TITLE
Add minimal voltage param

### LINKED ISSUE #93: Add parameter to configure minimum expected supply voltage

### PR DESCRIPTION
**Pull request by at-wat**
fix #93

### CODE REVIEW

**Comment by at-wat** [comment]
Tested locally with https://github.com/openspur/yp-spur/pull/151 on my robot.

**Comment by at-wat** [comment]
@seiga-k please take a look

**Comment by at-wat** [comment]
@seiga-k ping

**Review by seiga-k — APPROVED** [review]
LGTM

**Pull request merged**
