### PR TITLE
Add hall signal delay compensation

### LINKED ISSUE #38: Improve hall signal filtering
Since the hall sensor has a relatively large delay which makes phase error in high-speed operation, tf-2md3 doesn't rely on the hall signal by default.
This strategy works well for mobile robot wheel as their velocity often crosses zero. However, it can cause accumulated phase error on continuously rotating motors.

- [ ] make it easy to set the velocity threshold to use/ignore hall signal
- [ ] estimate hall signal delay and compensate delay on high speed

### LINKED ISSUE #71: Hall signal delay compensation
Hall sensor signal may have relatively large delay (tens of microseconds) due to LPF.

### PR DESCRIPTION
**Pull request by at-wat**
fix #71 
fix #38

### CODE REVIEW

**Comment by at-wat** [comment]
- [x] calculate rely-hall velocity threshold from params
---
- interrupt interval (100us at default) ~and hall signal delay~ should be less than 0.5%(= 1.8deg) of hall sinal interval (e.g. 3000rpm = 50Hz -> 20ms)
    - hall sinal interval [cycle]: `enc_rev` [cnt] / `vel` [cnt/cycle]
    - interrupt interval [cycle]: `control_cycle` [ms] / ((`48000` [kHz] / 2) / `PWM_resolution`)
```
interrupt interval [cycle] < hall sinal edge interval [cycle]
control_cycle [ms] / ((48000 [kHz] / 2) / PWM_resolution) < 0.005 * enc_rev [cnt] / vel [cnt/cycle]
vel < 0.005 * enc_rev [cnt] * ((48000 [kHz] / 2) / PWM_resolution) / control_cycle [ms]
vel < 0.005 * enc_rev [cnt] * 48000 [kHz] / (2 * PWM_resolution * control_cycle [ms])
```

**Comment by at-wat** [comment]
@seiga-k could you take a look this and also #73, #75, #76?

**Comment by seiga-k** [comment]
# About https://github.com/T-frog/tf-2md3-firmware/pull/73
##  tfrog-motordriver/controlPWM.c

I feel ```const int tan``` is not good naming. How about ```const int tan_th``` or something?

## Other 

LGTM

**Comment by seiga-k** [comment]
# About https://github.com/T-frog/tf-2md3-firmware/pull/75

LGTM

**Comment by seiga-k** [comment]
# About https://github.com/T-frog/tf-2md3-firmware/pull/76
## tfrog-motordriver/controlPWM.c

Is arm-gcc compiler promise a behavior of compile a modulo to less calculation method?
```c++
hall_pos = hall_pos % ENC0_BUF_MAX;
```

You limit ENC0_BUF_MAX as 2^n as bellow in ```tfrog-motordriver/controlVelocity.h```.
```c++
// ENC0_BUF_MAX must be 2^n to reduce computation cost.
#define ENC0_BUF_MAX 64
```

So, how about like this?
```c++
const int enc0_buf_mask = ENC0_BUF_MAX - 1;
hall_pos &= enc0_buf_mask;
```

**Comment by at-wat** [comment]
> Is arm-gcc compiler promise a behavior of compile a modulo to less calculation method?

I don't think bit mask is required as gcc don't use real modulo operation for immediate value divider, even if it is compiled with `-O0`.
I have added static assert to ensure it is power of two.

**Pull request merged**
